### ISSUE TITLE
Invalid parameter EPS_TIMESTAMP SecurePay Direct Post

### ISSUE THREAD

**Issue by mrizwanaarif** [thephpleague/omnipay-securepay#13]
Hi Everyone,

I am getting **"Invalid parameter EPS_TIMESTAMP"** Issue with SecurePay Direct Post.

I am using the below code to make a Http Post request.

`String mainURl = "https://test.api.securepay.com.au/directpost/authorise";

                ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(mainURl);

                var postData = string.Format("EPS_TIMESTAMP={0}", EPS_TIMESTAMP);
                postData += string.Format("&EPS_MERCHANT={0}", EPS_MERCHANGTID);
                postData += string.Format("&EPS_TXNTYPE={0}", EPS_TXNTYPE);
                postData += string.Format("&EPS_REFERENCEID={0}", EPS_REFERENCEID);
                postData += string.Format("&EPS_AMOUNT={0}", EPS_AMOUNT);
                postData += string.Format("&EPS_FINGERPRINT={0}", EPS_FINGERPRINT);
                postData += string.Format("&EPS_RESULTURL={0}", EPS_RESULTURL);

                var data = Encoding.ASCII.GetBytes(postData);

                request.Method = "POST";
                request.ContentType = "application/x-www-form-urlencoded";
                request.ContentLength = data.Length;

                using (var stream = request.GetRequestStream())
                {
                    stream.Write(data, 0, data.Length);
                }

                var response = (HttpWebResponse)request.GetResponse();

                var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();`

Thanks in Advance.

**Comment by njoshi00** [comment]
@mrizwanaarif  I am getting same error, how was it resolved ?

**Comment by Steffinarang** [comment]
Hi ,
can you please guide me. how you achieve this. i am doing same thing . i have one webpage and request a fingerprints to secure pay and response back from secure Pay. could you please share your code.
thanks
