### ISSUE TITLE
 Invalid parameter EPS_CARDNUMBER after POST redirection to SecurePay

### ISSUE THREAD

**Issue by makasim** [thephpleague/omnipay-securepay#3]
The documentation chapter [3.3.8 Card Information](http://test.web.securepay.com.au/resources/Direct_Post_Integration_Guide.pdf) tells us that all request must have credit card details, such as  "EPS_CARDNUMBER", "EPS_EXPIRYMONTH", "EPS_EXPIRYYEAR" and "EPS_CCV".  I cannot find any references in the code on these fields the Ominpay `card` is not used too.

Am I missing something or the library not finished?

**Comment by makasim** [comment]
ping @kayladnls @adrianmacneil

**Comment by amacneil** [comment]
It's finished and works, but I'll admit the documentation is lacking.

This gateway is a "transparent redirect" or "direct post" gateway (like eWay Rapid and a few others). You must first use omnipay to make the payment request, then use that to render a form to your customer, which they then submit directly to SecurePay. From the initial purchase response, you can use getRedirectUrl(), and use that to render a form to your customer.

```
<form method="post" action="(redirectUrl here)">
    <input name="EPS_CARDNUMBER">
</form>
```

etc

Sorry for the brevity, I don't have access to my development environment right now, but that should be enough to get you on the right path. I expanded on this a little more [here](https://groups.google.com/d/msg/omnipay/hjxBCU5blaU/T0jNekJSFScJ).

**Comment by makasim** [comment]
The problem is: I am getting `Invalid parameter EPS_CARDNUMBER` at securepay side after I was POST redirected there.
